### ISSUE TITLE
Editor Crash

### ISSUE THREAD

**Issue by Cop46** [turanszkij/WickedEngine#83] opened 2020-01-23 21:49 UTC
Hello,
I have tested your engine and this is awesone !!!
I have noticed some Crash, if I run the editor in Debug mode in VS2019 sometimes I have a crash at :
wGraphicsDevice_DX11.cpp at line 2660 deviceContexts[cmd]->CSSetShaderResources(slot, 1, &SRV); where &SRV containt strange value.
If I run the editor without VS2019 it crash always at startup and in Release mode it doesn't run to.
For the moment it's unstable but I love the pathtracing, that why I have tested your engine, because I search an engine that was capable to render with PathTracing.
Keep up the good work ;).

**Comment by turanszkij** [comment] 2020-01-23 22:08
Hi, sorry to hear you are having trouble. Are you running 32 bit or 64 bit version? Does it happen if you download the prebuilt version? (readme has download buttons for these, or from here: https://ci.appveyor.com/api/projects/turanszkij/wickedengine/artifacts/WickedEngineEditor.zip?branch=master&job=Platform%3A%20x64 )

Thanks for reporting the issue. I couldn't reproduce the crash on my PC.

**Comment by Cop46** [comment] 2020-01-23 22:21
I have compiled all projects in VS2019 in X64 mode on windows 10 with latest Nvidia Driver for the GTX1070 card.
I will try the prebuilt version.

**Comment by Cop46** [comment] 2020-01-23 22:36
The prebuilt version run perfect !
I will try to understand why the compiled version crash under my computer.

**Comment by turanszkij** [comment] 2020-01-23 22:48
It is strange, what version of Visual Studio 2019 are you using to build? Thanks.

**Comment by turanszkij** [comment] 2020-01-23 22:53
(I am using VS 2019 version 16.4.1 right now, auto build should be using version 16.4.3)

**Comment by Cop46** [comment] 2020-01-23 23:01
I use the 16.4.3 community edition

**Comment by turanszkij** [comment] 2020-01-23 23:13
I am using also the Community edition. This is strange. Maybe doing a full Clean + Rebuild of Editor project would fix the issue? Sometimes this can help.

**Comment by Cop46** [comment] 2020-01-24 20:56
Hi, I have tested many configuration and where I start the Editor from Visual Studio, there is no problem release and debug but when I execute the file without Visual Studio, it close when I load one mesh or one example. I think there is a problem with some path of files.

**Comment by turanszkij** [comment] 2020-04-20 13:51
Hi, since there were a lot of updates since you reported, this, did you have a chance to test a newer build? And the correct Editor path for working directory must be set to Editor folder.

**Comment by Cop46** [comment] 2020-04-25 07:20
Hello, I'm downloading your engine for new tests. Thanks for your notifications ;)

**Comment by Cop46** [comment] 2020-04-25 09:16
For first, all compilation mode work perfect release,debug,win32,win64 without made anything, just load sln,compil and start ! This is really comfurtable !

If that can help you,I have noticed some bugs.
Started with Visual Studio:
When activate MSAA some time it crash at client.h line 311 -> this = null.
In editor,Gui windows are to big, if I activate the path tracer and after reactivate Forward render path for example, the GUI take good size but appears to the exterior of my screen. I can just take a border to replace this.
Many bugs with this Gui system...Size of window, focus, sometimes click doesn't work first time....
In Path Tracer mode, if I change the bounce to 0, After that, this is impossible to move the camera.

Without visual studio impossible to try the editor correctly (I have tested in normal and admin):
If I load a model sometimes it crash,sometimes not.
If I add light it crash.
If I load scene it crash.

**Comment by turanszkij** [comment] 2020-04-25 11:33
Thanks for checking. The Editor should work without Visual Studio just fine, it seems there is some problem with how you launch it. The Editor.exe should be in the Editor folder, or the working directory set to the Editor folder.

About the other things:
- I will take a look at MSAA crash
- I know the GUI is not perfect, I am still improving it
- path tracer doesn't do anything with 0 bounces, I will modify the slider so the minimum value is 1 bounce

**Comment by Cop46** [comment] 2020-04-25 14:13
Yes, you are right, if I move the editor exe to the editor folder that work perfect !
For the msaa if that can help you, can just activate msaa and after add a simple light.

**Comment by Cop46** [comment] 2020-04-25 14:19
To avoid the crash for msaa you can change for ex in WiGraphicsDevice_DX11.cpp :
void GraphicsDevice_DX11::MSAAResolve(const Texture* pDst, const Texture* pSrc, CommandList cmd)
{
	assert(pDst != nullptr && pSrc != nullptr);
	auto internal_state_src = to_internal(pSrc);
	auto internal_state_dst = to_internal(pDst);
	if (internal_state_src != nullptr && internal_state_dst != nullptr)
	{
		deviceContexts[cmd]->ResolveSubresource(internal_state_dst->resource.Get(), 0, internal_state_src->resource.Get(), 0, _ConvertFormat(pDst->desc.Format));
	}
}

**Comment by turanszkij** [comment] 2020-04-25 14:30
MSAA bug was specific to the editor, it is fixed now in 7c8b88b4350764ef4d3f90916bc6a427f03b886c

**Comment by turanszkij** [comment] 2020-04-25 14:36
The path tracing bounce count slider is also fixed, minimum is 1 bounce now. The GUI problems are a long term issue, and it's managed in #51 

Thank you again for reporting the issues, I'm closing this now. :)

**Closed by turanszkij** 2020-04-25 14:36 UTC
Labels: bug
