### ISSUE TITLE
General puzzles

### ISSUE THREAD

**Issue by cailuming** [turanszkij/WickedEngine#268] opened 2021-06-06 13:48 UTC
Hi there, any demo to use tessellation ?  For instance, I want my planet to change vertices detail as camera moves

**Comment by turanszkij** [comment] 2021-06-06 14:28
Hi, there is no sample for that, but you can try tessellation in the editor for any mesh:

1. Open Renderer window and make sure "Tessellation" is enabled. It is enabled by default if you have GPU hardware that supports it, otherwise it's disabled.
2. Select any model (for example models/icosphere.obj to see the changes easily), and in the Mesh window adjust the "tessellation" slider. The greater the value, the more smoothed the object becomes closer to the camera.

In the code you can adjust the tessellation strength for a mesh with `MeshComponent::tessellationFactor`;

**Comment by cailuming** [comment] 2021-06-07 14:54
![err](https://user-images.githubusercontent.com/19427259/121037477-10017780-c7e2-11eb-8181-423306a96155.png)
![image](https://user-images.githubusercontent.com/19427259/121038916-3b389680-c7e3-11eb-8dba-52b5b86088c4.png)
![image](https://user-images.githubusercontent.com/19427259/121039041-560b0b00-c7e3-11eb-812b-a69bde2883aa.png)

Sorry for that but I ‘m failed to get the MeshComponent in the code. Nor can I reproduce tessellation in the editor. Am I missing some key point ?

**Comment by turanszkij** [comment] 2021-06-07 16:33
Tessellation in the editor seems to be not working in wireframe mode, it will be fixed. But it should work normally.

You fail to get the MeshComponent because the entity returned by the LoadModel is not an entity which has mesh component (it can be used as a parent transform). To get the MeshComponent, you will have to referencee it by the name. You can see the selected mesh name in the Editor mesh window on the top.

**Comment by turanszkij** [comment] 2021-06-07 19:11
The wireframe mode tessellation is fixed in https://github.com/turanszkij/WickedEngine/commit/f8a8c61b63004434b45e10cb56267d6dcad38313

**Comment by cailuming** [comment] 2021-06-08 14:51
![image](https://user-images.githubusercontent.com/19427259/121206515-1c9dd280-c8ab-11eb-85b9-6239b8d3ee1e.png)
![image](https://user-images.githubusercontent.com/19427259/121206824-5c64ba00-c8ab-11eb-923a-b26cc0ea4c89.png)
![image](https://user-images.githubusercontent.com/19427259/121206954-78685b80-c8ab-11eb-9b30-23fdfa7d5bcc.png)
![image](https://user-images.githubusercontent.com/19427259/121207210-b06f9e80-c8ab-11eb-8e41-0fe57d9c6fa7.png)
Good day, I encountered such  an odd case, where am I wrong

**Comment by turanszkij** [comment] 2021-06-08 16:40
The MeshComponent doesn't have a TransformComponent. What you are looking for probably is the "Object" (ObjectComponent). The way this engine works is that one MeshComponent can be used by lots of ObjectComponents (instancing). The entity which have an ObjectComponent will also have a TransformComponent. The ObjectComponent references the MeshComponent by a member variable, so this makes it possible for multiple objects to reference one mesh.

While it is possible to create a TransformComponent for a mesh, the engine will not use it in any way.

The entity that you get back from LoadModel also has a TransformComponent, so you can use that to move the whole model (it will be a topmost parent to everything).

Sorry if it's confusing.

**Comment by cailuming** [comment] 2021-06-09 14:37
My fault,you are kind enough though, I don't understand what you mean by "The MeshComponent doesn't have a TransformComponent" , I'm not trying to get a TransformComponent from MeshComponent, Following is what I want to do:
1. Load a model to scene
2. Get a specified entity(such as sphereEntity) for accessing other related component
3. Get a MeshComponent from scene.meshs by passing sphereEntity in, for setting TessellationFactor
4. Get a TransformComponent from scene.transforms by passing the same sphereEntity in , for translating the sphere
5. Watch the tessellation behavior

What I understand about Entity in this engine is that entity is just an index or ID of an Object, and Components which are ability or functionality for an object  can be attached to an entity. so I can retrive the one component from the wiScene by passing the entity in.

**Comment by turanszkij** [comment] 2021-06-09 14:46
You understand the entity-component system correctly. But the mesh instancing makes it a bit more complicated in this case. The entity that has a `MeshComponent`, **doesn't have** a `TransformComponent`. The entity that has `ObjectComponent` has a `TransformComponent`. The `ObjectComponent` has a `meshID` member variable that will reference a mesh. So you are most likely interested in the entity which has the `ObjectComponent`. So your scene could have:

entity1 -> MeshComponent
entity2 -> ObjectComponent + TransformComponent

entity2 -> ObjectComponent.meshID = entity1

I hope that can clear it up better

**Comment by cailuming** [comment] 2021-06-09 15:10
Yes,I think I'm clear, In order to share mesh, the wrapper ObjectComponent arises. Thanks alot!😁

**Comment by turanszkij** [comment] 2021-06-09 15:17
Yes, you got it. The editor mouse selection (if you click on an object) helps to select both entities at once, so you can also modify the mesh and the object too. Here is an image to help how to read the editor:
![Untitled](https://user-images.githubusercontent.com/12954849/121382031-84552b80-c946-11eb-90e2-9f17f88d3fc1.png)

**Comment by cailuming** [comment] 2021-06-14 03:40
![image](https://user-images.githubusercontent.com/19427259/121835958-12ddfa00-cd05-11eb-884a-94cb137752dc.png)
Hi, I encountered this crash when connect my joystick, what's going on?

**Comment by cailuming** [comment] 2021-06-14 05:07
And displacement seems not work
![image](https://user-images.githubusercontent.com/19427259/121841642-53437500-cd11-11eb-9205-da4ba3232204.png)

**Comment by turanszkij** [comment] 2021-06-14 08:45
About the joystick error: This is crashing in "wiRawInput" which is the handler for generic jostick. I tested it only for a PS3, PS4 controller and one fight stick I had. Unfortunately the generic gamepad detection is not very reliable. I tested now the PS5 controller and it is failing too in the same place as yours. I'll try to fix it but I don't know what the problem is. The XBOX controllers will be handled much more reliably, so I recommend that if you have one.

Displacement mapping: the shader implementation is now missing for it (it was removed some time ago while rewriting the shaders). I'll see if I can bring it back.

**Comment by turanszkij** [comment] 2021-06-14 09:08
The commit https://github.com/turanszkij/WickedEngine/commit/24994334025420c326051e58b279b38352358cb6 brings back the displacement mapping. Displacement mapping should be used with normal mapping, because it doesn't compute displaced normal vectors, only positions.

**Comment by cailuming** [comment] 2021-06-14 09:21
That is to say if I want to use displacement map , the according normal map is neccessary, right?

**Comment by turanszkij** [comment] 2021-06-14 09:26
Yes. By the way it only works with tessellation. And it can produce geometry cracks if the displacement texture is not perfectly mapped.

I'd also recommend to try parallax occlusion mapping which is displacement mapping per pixel. It can be nicer looking, but can't modify object silhouette. Also doesn't have to use tessellation and doesn't produce cracks. It needs to have a POM material shader to be set.

**Comment by cailuming** [comment] 2021-06-14 10:01
![image](https://user-images.githubusercontent.com/19427259/121873936-7aae3800-cd39-11eb-979c-28178a0d616b.png)
![image](https://user-images.githubusercontent.com/19427259/121874083-9d405100-cd39-11eb-9d85-cb6a18f7eba1.png)

Nice job,the parallax occlusion mapping looks good, but accually it has no shape, I'm thinking which to use depends

**Comment by turanszkij** [comment] 2021-06-14 13:23
I think I fixed the controller issue, at least now it works for the PS5 controller too, the problem was memory alignment in raw input. Commit: https://github.com/turanszkij/WickedEngine/commit/b6a1e0796af4eb2dc9c715899011ac5d1bfd3f7a

**Comment by cailuming** [comment] 2021-06-14 14:13
Nice ,My controller works too, I just found it's a matter of memory by GetLastError 
![image](https://user-images.githubusercontent.com/19427259/121905874-26b54a80-cd5d-11eb-9929-f2364c3bdf8b.png)
:joy:

**Comment by turanszkij** [comment] 2021-06-14 14:15
So it's good now and doesn't throw assert right?

**Comment by cailuming** [comment] 2021-06-14 14:16
Yes,you fixed it!

**Comment by turanszkij** [comment] 2021-06-14 16:21
Great, your feedback helps a lot, so let me know if you have other questions!

**Comment by cailuming** [comment] 2021-08-02 13:38
Hi, long time since last contact, I have trouble with moving camera, here is my code 
![image](https://user-images.githubusercontent.com/19427259/127870622-49e60a5e-ef8c-436c-9c9e-c4e193af170e.png)
but nothing happened when I press  the key 'W'

**Comment by turanszkij** [comment] 2021-08-02 13:42
You made a copy of the camera, try using a reference instead:
```cpp
CameraComponent& camera = wiScene::GetCamera();
```

**Comment by cailuming** [comment] 2021-08-02 13:49
Tks, it works, almost forget the reference because of getting used to other scripts

**Comment by cailuming** [comment] 2021-08-02 13:58
Another one , sometimes, It would crash when I click the run button.
![image](https://user-images.githubusercontent.com/19427259/127873195-33ffab23-1002-4685-a8a4-72c092434705.png)
and here is the call stack
![image](https://user-images.githubusercontent.com/19427259/127873344-a6c71918-c37a-44b8-8aef-29cac37ff38d.png)
![image](https://user-images.githubusercontent.com/19427259/127873440-79012448-2dce-4b84-ac20-b3a61fe35a7e.png)

**Comment by turanszkij** [comment] 2021-08-02 21:41
Hi, could you enable the following command line argument: 
```
debugdevice
```
And check if there is a D3D11 error reported on the output log in Visual Studio?

**Comment by cailuming** [comment] 2021-08-03 13:37
it seems not any D3D11 related error
![image](https://user-images.githubusercontent.com/19427259/128024856-fe7552f3-53b9-4326-b21f-60787da47756.png)
![image](https://user-images.githubusercontent.com/19427259/128024898-c5f4c83b-f9de-4045-adc6-ea39ec58bceb.png)
![image](https://user-images.githubusercontent.com/19427259/128024986-4e0f71a5-8582-4537-b337-666d5c23de4e.png)
Or I missed something

**Comment by turanszkij** [comment] 2021-08-03 14:24
Here is an example of the output log: 
![image](https://user-images.githubusercontent.com/12954849/128032453-812b78a7-56d2-4ed6-9324-2abed5eb099d.png)

**Comment by cailuming** [comment] 2021-08-03 14:43
D3D11 WARNING: ID3D11DeviceContext::CSSetUnorderedAccessViews: Resource being set to CS UnorderedAccessView slot 0 is still bound on input! [ STATE_SETTING WARNING #2097354: DEVICE_CSSETUNORDEREDACCESSVIEWS_HAZARD]
D3D11 WARNING: ID3D11DeviceContext::CSSetUnorderedAccessViews: Forcing CS shader resource slot 30 to NULL. [ STATE_SETTING WARNING #2097316: DEVICE_CSSETSHADERRESOURCES_HAZARD]
D3D11 WARNING: ID3D11DeviceContext::CSSetUnorderedAccessViews: Resource being set to CS UnorderedAccessView slot 0 is still bound on input! [ STATE_SETTING WARNING #2097354: DEVICE_CSSETUNORDEREDACCESSVIEWS_HAZARD]
D3D11 WARNING: ID3D11DeviceContext::CSSetUnorderedAccessViews: Forcing CS shader resource slot 31 to NULL. [ STATE_SETTING WARNING #2097316: DEVICE_CSSETSHADERRESOURCES_HAZARD]
D3D11 WARNING: ID3D11DeviceContext::DrawIndexedInstanced: The Pixel Shader expects a Render Target View bound to slot 0, but none is bound. This is OK, as writes of an unbound Render Target View are discarded. It is also possible the developer knows the data will not be used anyway. This is only a problem if the developer actually intended to bind a Render Target View here. [ EXECUTION WARNING #3146081: DEVICE_DRAW_RENDERTARGETVIEW_NOT_SET]
0x00007FFE3256F3C8 (d3d11.dll)处(位于 Template_Windows.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000130 时发生访问冲突。


I dont know whether it's what you talk, or I also need enable the D3D device debug layer flag

**Comment by turanszkij** [comment] 2021-08-03 14:45
Yes this is it, but there are no errors here. Is this the log at the time of the crash?

**Comment by cailuming** [comment] 2021-08-03 14:48
Yes, the log borns along the crash just now, And I can reproduce it when I restart frequently

**Comment by cailuming** [comment] 2021-08-03 14:56
By the way, my repository isnt the latest. I will keep it update and test what happened tomorrow

**Comment by cailuming** [comment] 2021-08-04 13:51
There is no problem  for Editor project , but my modified Template_Windows will crash , perhaps it's my personal mistake
![image](https://user-images.githubusercontent.com/19427259/128192663-ee668579-bae8-40a6-8761-52f07d96821f.png)

**Comment by turanszkij** [comment] 2021-08-04 20:10
Sorry, I have no clue at the moment, you could also try running with DX12 or Vulkan. Just enter either `dx12` or `vulkan` as command line arguments.

**Comment by cailuming** [comment] 2021-08-05 01:31
It's ok, I'll try it and feedback later

**Comment by cailuming** [comment] 2021-08-07 12:12
It seems  both DX12 and Vulkan are fine

**Comment by turanszkij** [comment] 2021-10-10 17:12
This highlighted an issue for me, the font render uses a slightly wrong blend state, I fixed it in: https://github.com/turanszkij/WickedEngine/commit/e3611fba20df88357ef509b15adee50209680377

**Closed** 2021-11-09 10:30 UTC
Labels: support
