### ISSUE TITLE
Need support in HairParticle

### ISSUE THREAD

**Issue by cailuming** [turanszkij/WickedEngine#261] opened 2021-05-05 05:45 UTC
![image](https://user-images.githubusercontent.com/19427259/117100583-ac30fc80-ada6-11eb-86ab-92354f0e798e.png)
Hi, I don't know how to get the  index of specified Entity, For example ,when I want to create a HairParticle, I must create a hair entity and get the wiHairParticle component from the hair entity. And then I have to specify a base mesh entity to the meshID of HairParticle. As you can see from the picture above, I want to load something like a plane, I use the wiScene::LoadModel, But here comes the problem, I have no idea about how to get the entity I just load. And I found that the return value of wiScene::LoadModel is type of entity, but it may be invalid if we pass false args.

**Comment by turanszkij** [comment] 2021-05-05 08:22
Hi, you can use `scene.Entity_FindByName("meshName")`. This will return an entity if one exists with that name. If multiple entities exist with the same name, the first one will be returned (so I recommend to have unique entity names). 

You can also set up hair particle systems inside the editor, and use the paint tool to place particles onto the mesh surface. Let me know if you need more info.

**Comment by cailuming** [comment] 2021-05-05 11:51
I got it, and I works as I expected finally. Another issue is the jagged edge on the texture alpha blending, or may be alpha testing? 
![image](https://user-images.githubusercontent.com/19427259/117131469-0dbb9000-add4-11eb-8450-a261e4572a18.png)
The original texture looks like this
![image](https://user-images.githubusercontent.com/19427259/117131656-478c9680-add4-11eb-98c2-62c8e4a5d651.png)
It seems that the original texture does not looks worse than on the final rendering. Maybe it's just a matter of Anti-aliasing?

By the way, I have tried to use paint tool in editor, but still confusing about how to use, such as add/remove trangle on HairParticle , when I select it and paint on the focused grass, nothing happened, Or I need to go through the related source code

**Comment by turanszkij** [comment] 2021-05-05 12:40
The jaggedness is due to alpha testing. There is no alpha blending supported now for the grass (it is too expensive to have sorting, blending and multi layered lighting). You can modify the alpha testing threshold by selecting the hair particle system in the Editor, then going to the Material window, where you can adjust the "AlphaRef" slider.

The paint tool for hair is a bit hard to use, I admit.  There are three modes for HairParticle:
- Add triangle: selected triangles of the mesh will generate particles (shown in purple debug color if the "wireframe" checkbox is enabled)
- Remove triangle: selected triangles will be removed from the hair, they will no longer generate particles (so remove triangles shown in purple debug color)
- Length: paint particle length on the mesh regions. Use the color picker's alpha slider for the value (0-1) to specify lengths. The other brush properties will also affect how the length weight is applied

You must also set the particle count on the hair particle system to see something, otherwise you might not see anything if there are no particles.

For example, try using the Content/models/hairparticle_torus.wiscene model. There are two hair particle systems on it, a grass and a flower one, so you could delete one of them to make it easier to see how it works.

**Comment by cailuming** [comment] 2021-05-05 13:05
Thanks for your help, I will try it

**Comment by cailuming** [comment] 2021-05-05 14:24
Yes,it does work. 
Another one, actually, is not a big problem for me, I found the weather default cloud behaves 2d fbm manner, and the cloud properties couldn't affect the volume cloud in Postprocess.  Could we merge the properties between the default cloud and volume cloud? Or at least expose  the properties of  volume cloud to user .

**Comment by turanszkij** [comment] 2021-05-06 08:03
Yes, the volume cloud parameters should be exposed, at least some of them. I will see how it makes the most sense. I don't know what you meant by "2d fbm manner"

**Comment by cailuming** [comment] 2021-05-06 09:14
I'm sorry for my bad english, I mean the default weather cloud looks like a piece of thin paper even though it may be faster. the volume cloud looks better,haha 
By the way, do we have SkinedAnimation baking component ?

**Comment by turanszkij** [comment] 2021-05-06 09:55
No problem and yes, the default cloud is much simpler to render, but it's 2D. 

SkinnedAnimation baking? Skinned animations are supported, but not baking, I'm not sure what would you want to bake in it?

**Comment by cailuming** [comment] 2021-05-06 10:40
I mean the skined animation data can be baked into texture for GPU instancing , or we have the character skined animation GPU instancing  already?

**Comment by turanszkij** [comment] 2021-05-06 12:24
Skinning is computed on GPU. If you instance it, then the same animation pose will be repeated for the new instance, since the skinning is only computed once by compute shader, not for every draw. This makes it compatible with raytracing too. If you duplicate mesh, then a new skinning with new animation can be applied, however it won't be instanced. So there is no way currently to have one draw call for multiple instances but different skinning animation. I think this skinning system should be still pretty fast.

**Comment by cailuming** [comment] 2021-05-06 15:10
So our skined animation data ,aka all frames will be pre computed and stored into buffer , and then,we just fetch the specifed bone data and weights,right? 
BTW, I found the "USE_LDS" macro, which is disable by default, what's the difference? 
![image](https://user-images.githubusercontent.com/19427259/117322014-34ef8b80-aec0-11eb-9c7c-4901b7ebdb12.png)

**Comment by cailuming** [comment] 2021-05-06 15:13
Oh god, I happened to find your blog about the skined animation ,I should learn it first 
![image](https://user-images.githubusercontent.com/19427259/117322544-ae877980-aec0-11eb-9936-b81400277e4b.png)

**Comment by turanszkij** [comment] 2021-05-06 15:19
One frame of animation data is computed every frame on CPU, and bone data for that frame is uploaded to GPU. The USE_LDS is a kind of experimental optimization, there is a variant of skinning shader that uses it (skinningCS_LDS.hlsl) and one that doesn't (skinningCS.hlsl). The LDS version is used when the entire bone data fits into the groupshared memory, though this can be turned off by `wiRenderer::SetLDSSkinningEnabled(false)`. 
All the meshes that have skeletons are skinned in the beginning of the frame once, before any rendering happens. Their result will be written to the `MeshComponent::streamoutBuffer_POS` (positions, normals) and `streamoutBuffer_TAN` (tangents) and these will be used as vertex buffers from that point.

**Comment by cailuming** [comment] 2021-05-07 05:11
"One frame of animation data is computed every frame on CPU" , I'm even more confused, that is to say, each animation frame data will be computed during each rendering frame ? that does'nt make any sense. ٩( 'ω' )و

**Comment by turanszkij** [comment] 2021-05-07 08:40
What I mean is animation bone matrices are computed on the CPU, and the skinning of vertices is done on GPU. These are done every frame.

**Comment by cailuming** [comment] 2021-05-07 14:19
So this makes sense,I got it.
![image](https://user-images.githubusercontent.com/19427259/117462389-3339cc80-af81-11eb-96ab-2bf0c3f7d3a5.png)

I don't mean that,but have you noticed the jagged edges? When I turn on fog, as the picture shows, it appears a downside rendering rate around the edge.while I turn off the fog, it looks right:smirk:

**Comment by turanszkij** [comment] 2021-05-07 17:27
That is caused by volumetric lights (which are affected by fog). It is because volumetric lights are rendered in quarter resolution and later upsampled to save performance. If you would like to try increase the volumetric light resolution, you can modify that in RenderPath3D.cpp: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/RenderPath3D.cpp#L94

The volumetric light can be enabled/disabled per light with `LightComponent::SetVolumetricsEnabled(true)` or the Light window in Editor.

**Comment by cailuming** [comment] 2021-05-08 14:57
Thank you, sorry for another question which is related to Emiter, as you can see from the picture
![image](https://user-images.githubusercontent.com/19427259/117543387-2f747b80-b04f-11eb-89b6-b7e787b22316.png)
I want to simulate a tail flame, but I couldn't find where to set the start and end size of particle, It seams that there is only size option of the entire emiter. What's more, when I slide the scaling up, the frame rate is cutted down rapidly, I don't know why.. 
//ㄒoㄒ//

**Comment by turanszkij** [comment] 2021-05-08 17:20
The "size" slider sets the particle starting size. 
The "scale" slider sets the scaling (size * scaling) factor at the end of particle's life.
Large particles will be much slower to render, so look out for that.

**Comment by cailuming** [comment] 2021-05-09 02:20
If I want to change weapon or equipment for my character, what should I do with the ArmatureComponent.
How should I get the specified bone and attach something to it

**Comment by cailuming** [comment] 2021-05-09 03:00
Hi, I found a problem again, lots of holes appear on the sphere when I click ComputeNormals(SMOOTH)
![image](https://user-images.githubusercontent.com/19427259/117559166-bc522000-b0b5-11eb-9fe8-d6968e380646.png)

**Comment by turanszkij** [comment] 2021-05-09 07:13
You can attach an enitity to an other entity with `Scene::Component_Attach(entity, parent_entity)`. You could use the weapon entity and attach it to one of the bone entities. You can use the `Scene::Entity_FindByName(name)` to get a bone with a specific name.

About the spehere mesh recompute normals: I couldn't reproduce this issue, I tried with the uvsphere.obj and the icosphere.obj files that are in the models folder, but it worked as expected. Could you share the mesh you are having problem with?

**Comment by cailuming** [comment] 2021-05-09 07:41
Of course, but I couldn't find how to share it with you,  the sphere is purely created and  exported from blender as glb format. And if you still failed to repeat the case,  may be you can leave me a valid email address

**Comment by turanszkij** [comment] 2021-05-09 07:46
You could attach it to this issue for example

**Comment by cailuming** [comment] 2021-05-09 07:49
![sphere](https://user-images.githubusercontent.com/19427259/117564285-fc2cfd80-b0dd-11eb-9d60-65f83ed4cb6c.gif)
I just modified the file extension to be able to upload, original extension is glb

**Comment by cailuming** [comment] 2021-05-09 08:07
My pleasure, that is to say the base functionality of code is ok, it's just a matter of calling in editor

**Comment by turanszkij** [comment] 2021-05-09 12:50
It's fixed in https://github.com/turanszkij/WickedEngine/commit/2cf3b7708a9996025f814b3913bf1caabb9c865d

**Comment by cailuming** [comment] 2021-05-09 13:32
Thank you, another one, is there any method to modify the atmosphere radius ? And also,  ocean system is still rendering or buzy with computing when out of far plane, this of course can be set inactive manually. But I want to make sure whether ocean system is culling automatically.
![image](https://user-images.githubusercontent.com/19427259/117574085-0535c300-b10e-11eb-8e8d-789748392b1e.png)

**Comment by turanszkij** [comment] 2021-05-09 13:38
The radius parameters are currently hard coded in the shader, here: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/shaders/skyAtmosphere.hlsli#L72
I will consider exposing these parameters in the weather probably.

The ocean is not capable of determining when to update itself right now, but it can be implemented.

**Comment by cailuming** [comment] 2021-05-09 13:44
Got it, thank you!

**Comment by cailuming** [comment] 2021-05-17 14:58
Hi there , do we plan to add foam rendering to OceanComponent?  or I can render foam according chopness info by myself,I don't know. Any tips?

**Comment by turanszkij** [comment] 2021-05-17 15:23
> Hi there , do we plan to add foam rendering to OceanComponent? or I can render foam according chopness info by myself,I don't know. Any tips?

It would be cool to implement, but I'm not sure when I get around to do it. If you find a good way to render them, let me know.

**Comment by cailuming** [comment] 2021-05-23 13:53
Hi, I have no idea about how to make a cube volume particle emitter, such as rain or snow.  not just emitted from one point

**Comment by turanszkij** [comment] 2021-05-23 14:01
Hi,
here is a sample rain emitter emitted from a volume. The emitter window has a "Volume" checkbox, that will make the particles spawn inside a bounding box (emitter can be scaled or positioned,etc). An other option is to set a mesh and emit from mesh surface.

[emitter_rain100k.zip](https://github.com/turanszkij/WickedEngine/files/6528195/emitter_rain100k.zip)

**Comment by cailuming** [comment] 2021-05-23 14:26
Nice rain, Thank you so much,  I think I stucked at not knowing to scale the volume

**Closed** 2021-06-06 13:41 UTC
Labels: support
