### ISSUE TITLE
(Linux) Mouse Delta is Jumpy

### ISSUE THREAD

**Issue by megumumpkin** [turanszkij/WickedEngine#698] opened 2023-06-21 16:27 UTC
So when the framerate is low, it would jump to the reverse direction or stop.
It's kind of like the cursor is edging to the constraints of the window.
This is more apparent when the cursor is set near at one of the edge of the window.
All this happens while i'm using the cursor-disabling third person camera code from wicked, which always re-put the cursor the the location before the cursor locking.
It would more often jump to the opposite direction of the cursor when nearing the edges of the window, kind of like bouncing back.
At high framerate, this would seldom appear, as the delta distance is smaller and won't reach the edge of the window i think..

**Comment by turanszkij** [comment] 2023-09-04 11:56
Maybe this is related? https://github.com/turanszkij/WickedEngine/pull/740

**Comment by Jontte** [comment] 2023-09-10 08:16
The jumpiness is probably caused by the fact that the SDL2 event handler code is only processing the latest relative mouse motion event and ignoring the rest, meaning behavior will vary wildly for users with different frame rates. I suggested a fix in #740

**Comment by turanszkij** [comment] 2023-09-15 06:07
As #740 is merged, as I understand this is fixed.

**Closed by turanszkij** 2023-09-15 06:07 UTC
