### ISSUE TITLE
Crash at startup on Linux (version 0.71.209)

### ISSUE THREAD

**Issue by Froyok** [turanszkij/WickedEngine#684] opened 2023-05-24 11:49 UTC
Heya ! :wave: 
I wanted to try out the engine via the Steam binaries on Linux, however it crashes after a few seconds.
Basically the window appears, the initial debug information on the top left appears, but the screen is otherwise black and the engine then shutdown.

(I have looked around but haven't seen similar reports, so sorry in advance if that's a duplicate.)

My specs:

- Linux Manjaro (5.15.112-1)
- KDE Plasma (5.27.4)
- Mesa 23.0.3
- AMD Radeon RX 5600 XT
- Ryzen 9 3900X

I'm on Manjaro (Arch based) and not Ubuntu, so it's fine if you say "I don't support it". Let me know if you need additional information however.

From the terminal I get the following information:
```
/bin/sh\0-c\0/home/froyok/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1967460 -- /home/froyok/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/data/Games/Steam/steamapps/common/Wicked Engine/Editor_Linux'\0
Game process added : AppID 1967460 "/home/froyok/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1967460 -- /home/froyok/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/data/Games/Steam/steamapps/common/Wicked Engine/Editor_Linux'", ProcID 273253, IP 0.0.0.0:0
chdir /mnt/data/Games/Steam/steamapps/common/Wicked Engine
GameAction [AppID 1967460, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 1967460, ActionID 4] : LaunchApp changed task to Completed with ""
config.ini loaded in 0.114587 milliseconds

Fossilize INFO: Overriding serialization path: "/mnt/data/Games/Steam/steamapps/shadercache/1967460/fozpipelinesv6/steamapprun_pipeline_cache".
[Warning] File not found: /tmp/wiPipelineCache_Vulkan
Created GraphicsDevice_Vulkan (39 ms)
Adapter: AMD Radeon RX 5600 XT

[wi::initializer] Initializing Wicked Engine, please wait...
Version: 0.71.209
Embedded shaders found: 354

wi::jobsystem Initialized with [24 cores] [23 threads] (1 ms)

wi::physics Initialized [Bullet] (0 ms)
wi::input Initialized (10 ms)
wi::font Initialized (11 ms)
wi::lua Initialized (17 ms)
wi::texturehelper Initialized (8 ms)
wi::GPUBVH Initialized (48 ms)
wi::audio Initialized [FAudio] (63 ms)
wi::image Initialized (64 ms)
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
Game process removed: AppID 1967460 "/home/froyok/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=1967460 -- /home/froyok/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/mnt/data/Games/Steam/steamapps/common/Wicked Engine/Editor_Linux'", ProcID 273253 
Uploaded AppInterfaceStats to Steam
```

**Comment by turanszkij** [comment] 2023-05-24 13:51
Hi, thanks for reporting it. This is strange, seems to complain about some file system stuff:
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
```
Unfortunately the error message doesn't say where it is coming from. This will need to be investigated by someone with a debugger who can also repro the issue.

Do your paths contain any special characters perhaps, like non-english letters? Although on your console log I don't see anything like that.

**Comment by portaloffreedom** [comment] 2023-05-24 14:05
I have the same issue when launching the steam version. Running my locally compiled engine instead works fine.
Could it be an issue caused by the embedded shaders?

**Comment by turanszkij** [comment] 2023-05-24 14:14
Could you try removing the `languages/日本語.xml` file from the steam app install location? For me (on Windows) is:
```
C:\Program Files (x86)\Steam\steamapps\common\Wicked Engine\languages
```

There seems to be an issue with this filename that contains special characters. There is probably some incompatibility with Linux in the function that gets all file names from a directory: https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/wiHelper.cpp#L1163

**Comment by Froyok** [comment] 2023-05-24 14:16
Removing the file `日本語.xml` seems to be working, the engine now starts and I can see the UI (menu + icons) as well as the default grid. I can move the camera freely. :)

**Comment by turanszkij** [comment] 2023-05-24 14:28
Ok, thanks for checking! Matteo identified the issue with std::filesystem::path::generic_wstring() not working on some compilers on Linux, and it is fixed in this commit: https://github.com/turanszkij/WickedEngine/commit/1475a34185fee12c899b5fcd947bc07a3e4af89d
Steam version will be updated shortly.

**Closed** 2023-05-24 15:48 UTC
